// File generated by Antigravity (Manually populated due to CLI environment restrictions)
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY'] ?? '',
        appId: '1:668401123677:web:60525ae23003c38e9c68b4',
        messagingSenderId: '668401123677',
        projectId: 'calorai-366f4',
        authDomain: 'calorai-366f4.firebaseapp.com',
        storageBucket: 'calorai-366f4.firebasestorage.app',
        measurementId: 'G-WSR72RMFC9',
      );

  static FirebaseOptions get windows => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY'] ?? '',
        appId: '1:668401123677:web:60525ae23003c38e9c68b4',
        messagingSenderId: '668401123677',
        projectId: 'calorai-366f4',
        authDomain: 'calorai-366f4.firebaseapp.com',
        storageBucket: 'calorai-366f4.firebasestorage.app',
        measurementId: 'G-WSR72RMFC9',
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY'] ?? '',
        appId: '1:668401123677:android:1b99e9a88a6337f99c68b4',
        messagingSenderId: '668401123677',
        projectId: 'calorai-366f4',
        storageBucket: 'calorai-366f4.firebasestorage.app',
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ?? '',
        appId: '1:668401123677:ios:8fc15c17d33c79df9c68b4',
        messagingSenderId: '668401123677',
        projectId: 'calorai-366f4',
        storageBucket: 'calorai-366f4.firebasestorage.app',
        iosBundleId: 'com.example.calorai',
      );
}
